"""Add StagedRecord

Revision ID: 3cc5d6e3a60d
Revises: 0003_bridges
Create Date: 2026-07-01 14:09:42.013811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc5d6e3a60d'
down_revision: Union[str, Sequence[str], None] = '0003_bridges'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=200), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.create_index('ix_staged_records_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_staged_records_job_order', ['job_id', 'order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_records_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('bridges', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridges', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_records_org_id'))
        batch_op.drop_index('ix_staged_records_job_order')
        batch_op.drop_index(batch_op.f('ix_staged_records_job_id'))
        batch_op.drop_index('ix_staged_records_created_at')

    op.drop_table('staged_records')
    # ### end Alembic commands ###
